language: python

sudo: false

env:
  global:
  - OPENBLAS_NUM_THREADS=1
  - OMP_NUM_THREADS=1

matrix:
  allow_failures:
  - os: osx
  
  include:
  - os: linux
    env: DISTRIB="conda" PYTHON_VERSION="3.4" MINICONDA_URL="https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh"
  - os: linux
    env: DISTRIB="conda" PYTHON_VERSION="3.5" COVERAGE="true" MINICONDA_URL="https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh"

  # Set language to generic to not break travis-ci
  # https://github.com/travis-ci/travis-ci/issues/2312#issuecomment-195620855
  # so far, this issue is still open and there is no good solution
  # python will then be installed by anaconda
  - os: osx
    sudo: required
    language: generic
    env: DISTRIB="conda" PYTHON_VERSION="3.4" MINICONDA_URL="https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh"
  - os: osx
    sudo: required
    language: generic
    env: DISTRIB="conda" PYTHON_VERSION="3.5" MINICONDA_URL="https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh"

cache:
  # We use three different cache directory
  # to work around a Travis bug with multi-platform cache
  directories:
  - $HOME/.cache/pip
  - $HOME/download
  pip: true

git:
  depth: 5

env:
  global:
  # Directory where tests are run from
  - TEST_DIR=/tmp/test_dir/
  - MODULE=autosklearn

before_install:
  - wget $MINICONDA_URL -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - if [[ `which conda` ]]; then echo 'Conda installation successful'; else exit 1; fi
  - conda update --yes conda
  - conda create -n testenv --yes python=$PYTHON_VERSION pip wheel nose
  - source activate testenv
  - conda install --yes gcc
  - echo "Using GCC at "`which gcc`
  - export CC=`which gcc`
  # Fixes version `GLIBCXX_3.4.21' not found (on Ubuntu 16.04)
  - conda install --yes libgcc

install:
  - pip install coverage pep8 python-coveralls
  - cat requirements.txt | xargs -n 1 -L 1 pip install
  # For Auto-Net dependencies
  - pip install theano nose_parameterized
  - pip install git+https://github.com/hmendozap/Lasagne
  - python setup.py install
  
script: bash ci_scripts/test.sh
after_success: source ci_scripts/success.sh

